### ISSUE TITLE
Formatter indents on ternary operator

### ISSUE THREAD

**Issue by ewerybody** [mark-wiemer/vscode-autohotkey-plus-plus#18]
**Repro**
1. have sth like this code (this is from the [original docs](https://lexikos.github.io/v2/docs/Variables.htm#ternary) just with quotes around the 3)
```Autohotkey
var := x>y ? 2 : "3"
something("skdfjbv")
```
2. Perform **Format Document** with AHK++ >
```Autohotkey
var := x>y ? 2 : "3"
    something("skdfjbv")
```

The exact expression from the docs `var := x>y ? 2 : 3` does work properly tho!
It's just when there is a quoted string after the `:`

**Expected behavior**
The code should not change.

**Environment**

VS Code **1.53.0.0**
AutoHotkey Plus Plus **v2.5.12**

**Comment by ewerybody** [comment]
I would actually like to have a look into this myself but I have NO idea where to start as I'm not into TS or Electron at all. But that can change :) 

I guess everything is already build-in to VS Code? To debug TS? Where would I start setting breakpoints? Can I debug the running VS Code while coding it ... ?!?! 🤔

**Comment by FuPeiJiang** [comment]
to help understand: since strings are removed, it becomes `var := x>y ? 2 :`(var purityText in \vscode-autohotkey-plus-plus\src\provider\formattingProvider.ts), and anything that ends with `:` is considered a hotkey, so it is indented

my git is kinda messed up right now... I'm learning how to use, now I have time
I will try to fix this after

**Comment by ewerybody** [comment]
hmm. But 
```Autohotkey
var := x>y ? 2 : 3
something("skdfjbv")
```
remains unchainged!

After all: I think we need some tests for the formatter at best on various bigger libraries and.

**Comment by FuPeiJiang** [comment]
3 is not a string
I said strings are removed
3 here is a number

**Comment by fade2gray** [comment]
@ewerybody 
Maybe this might help understand. Try formatting this.

```
;Formatting ignores any string after the colon
;making the ternary act like a hotkey.
var := x>y ? 1 : 2 ;<< Integer after tthe : is ok
;identation no
var := x>y ? 1 : ;<< no "string" causing indentation
;everything indented
;until something
;ends with a : or  : "string" or Return
var := x>y ? 1 : "" ;<< "string" ignored causing indentation
;everything indented
;until something
;ends with a : or  : "string" or Return
HotKey:
;everything indented
;until something
;ends with a : or  : "string" or Return
Return
```

**Comment by ewerybody** [comment]
Ah ok. I didn't get what you mean with "strings removed". Thought you mean quotes removed or something.
**"string" ignored** is a little more clear. Thanks @fade2gray 
But what about the `;` why aren't these ignored? See:
```autohotkey
;Formatting ignores any string after the colon
;making the ternary operator act like a hotkey.
var := x>y ? 1 : 2 ;<< Integer after tthe : is ok
;identation no
var := x>y ? 1 : ;
;identation no
var := x>y ? 1 : "2" ;
;identation no
HotKey:;
;identation no
Return
```

**Comment by fade2gray** [comment]
Because the ternary operator is only affected if the colon is followed by a **string** or **nothing at all.** Your example has the colon followed by a **space+semicolon**.

**Comment by FuPeiJiang** [comment]
> **"string" ignored** is a little more clear.

noted
>But what about the ; why aren't these ignored? See:

ty for finding this, this isn't supposed to happen, since one `;` is a comment too
the reason for this is:
`.replace(/;.+/, '')` + is one or more
if you use this instead, the empty comment will be ignored, (I like to say removed because it's being replaced with empty string)
``.replace(/;.*/, '')`` * is zero or more

this is in function `CodeUtil.purity` of `\vscode-autohotkey-plus-plus\src\common\codeUtil.ts`

but I suspect that changing ONLY this regex won't fix the problem of matching comments properly...
since ``  `; `` is not a comment

I will try to fix these, after...
