### ISSUE TITLE
Block/Multiple-line commenting

### ISSUE THREAD

**Issue by tdalon** [mark-wiemer/vscode-autohotkey-plus-plus#77]
I would like the possibility to multiple lines/block comment/ uncomment selected code lines like in AHK-Studio.

This include the selected code between /* */
See screenshot attached.
![image](https://user-images.githubusercontent.com/6458444/111779611-a5156400-88b6-11eb-95dd-00b6389acb31.png)

The block is nicely indented and color-highlighted.
One shouldn't need to select the comment block but it will get it from the cursor position and take the block around it.

**Comment by fade2gray** [comment]
Try this...

```ahk
;region
These tags will create a
folding region of code
that doesn't require
indentation
;endregion

/* ;region
Prefixing with /* and */
will create a folding
block comment
*/ ;endregion
```

**Comment by tdalon** [comment]
> Try this...
> 
> ```ahk
> ;region
> These tags will create a
> folding region of code
> that doesn't require
> indentation
> ;endregion
> 
> /* ;region
> Prefixing with /* and */
> will create a folding
> block comment
> */ ;endregion
> ```

As written in the issue description: I would know how to do this manually. The request here is to have this built-in in the extension. Also adding some additionally features with indenting and color formatting. The feature shall also toggle the block on and off.

**Comment by fade2gray** [comment]
@tdalon Sorry, didn't read beyond the image.

I bought up a similar request [here](https://github.com/mark-wiemer/vscode-autohotkey-plus-plus/issues/5), so @mark-wiemer  might have something on the back-burner.

But, I have created myself a simplistic helper script that can automatically add and remove the folding/comment tags, though it does need the block of code to be highlighted. I could post it in the discussion section if you want to make use of it.

![EasyFolding](https://user-images.githubusercontent.com/1332009/112644809-bb369d80-8e3d-11eb-919e-0bd27ef90e04.png)

**Comment by mark-wiemer** [comment]
This is a good one! I've been meaning to simplify the foldable region snippet for a while, thanks for reporting this

**Comment by mark-wiemer** [comment]
Alright, I misunderstood this as folding block comments, not toggling block comments. My mistake.

For toggling block comments, VS Code's built-in commands should be sufficient. There is `expand selection` which can be applied repeatedly to highlight the block, and then we can finish with `toggle block comment`. Both are accessible through the command palette and have default keyboard shortcuts that are re-mappable as well.

The color will stay the default "comment" color (usually green) since I don't see a need (or way) to distinguish between plain comments and commented code.

I'm going to add folding for non-indented block comments, even though that's beyond the scope of this issue.

Closing this issue since there is a sufficient workaround with built-in features.

**Comment by FuPeiJiang** [comment]
this is literally selecting code block, which requires a parser
https://github.com/wangchunsen/vscode-bracket-select
https://github.com/FuPeiJiang/vscode-bracket-select/releases/tag/2.0.1
here, I've used typescript parser (pretty inefficiently) to select code block

ripppp, no ahk parser, yet.
though, https://github.com/zero-plusplus/vscode-autohotkey-debug/discussions/90#discussioncomment-1698051
I think there is ?
