### ISSUE TITLE
Run command is not working 

### ISSUE THREAD

**Issue by eb0687** [mark-wiemer/vscode-autohotkey-plus-plus#95]
Not sure if this is an issue with the AHK++ plugin, but when I try to use the RUN command to launch an application from a directory it doesn't work, nothing happens at all.

But when trying the same exact thing in SCITE is works fine.

Is this a known issue? or am I missing something here?

**Comment by fade2gray** [comment]
If by "application" you mean AHK script, I don't believe there's a method to launch it in that manner, but you can open a script via the file menu then right-click in the open editor and select `Run AHK Script` from the context menu or use the `(Ctrl+F9)` shortcut.

**Comment by eb0687** [comment]
no no, by application I just mean any .exe file.

For example:

!^1::Run, C:\Program Files\Notepad++

it does not launch the file for some reason when I use the hotkey in vscode, but the same works in scite

**Comment by fade2gray** [comment]
Firstly, the `Notepad++` directory is missing from the path; secondly, there is a `space` in the path so should be enclosed in quotes.


``` ahk
^1::Run, "C:\Program Files\Notepad++\notepad++.exe"
````

**Comment by FuPeiJiang** [comment]
I think a made a script "f5 to run ahk.ahk" for this exact reason: an ahk script ran by vscode cannot run vscode ??
I put "f5 to run ahk.ahk" in "shell:common startup" or "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp"
now it's started by Windows startup instead of vscode subprocess ??
perhaps it's possible to do it correctly in vscode, I first need to look if this extension does it wrong, but I don't want to

in vscode settings.json put : `"window.title": "${activeEditorLong} - Visual Studio Code",`
now you can grab longPath from WinTitle using AHK : [WinGetTitle](https://www.autohotkey.com/docs/commands/WinGetTitle.htm)

**Comment by fade2gray** [comment]
Perhaps I'm misunderstanding the OP - I've never used SciTe to any great degree  - I'll just go and sit at the back of the class. ¯\_(ツ)_/¯

**Comment by FuPeiJiang** [comment]
> Perhaps I'm misunderstanding the OP

we are all guessing, OP wasn't very clear at the start.
you asked, OP clarified, then I was interested

sit back of the class ? there's no class though. more like try SciTe, running it yourself, better than any class
___
```
; Run, C:\Program Files (x86)\Notepad++\notepad++.exe ;#1
Run, C:\Users\User\AppData\Local\Programs\Microsoft VS Code\Code.exe ;#2
```
Debug AHK Script (F9) (button: white triangle) : #1 works, #2 doesn't work
Run Code (Ctrl + Alt + N) (button: black triangle with white border) : #1 works, #2 works

Run Code is from Code Runner : https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner
you can see that it will run this : `autohotkey "c:\run stuff.ahk"`

@eb0687 which button did you click ? or which VsCode command ? What exactly did you ahk RUN ? notepad++.exe ? because now I suspect vscode.exe

**Comment by fade2gray** [comment]
Are you sure there should be a leading semicolon on the first line?
```ahk
; Run, C:\Program Files (x86)\Notepad++\notepad++.exe ;#1
Run, C:\Users\User\AppData\Local\Programs\Microsoft VS Code\Code.exe ;#2
```

My paths are ...
```ahk
Run, C:\Program Files\Notepad++\notepad++.exe ;#1
Run, C:\Program Files\Microsoft VS Code\Code.exe ;#2
```
Using AHK++ F9 or  Ctrl+F9 ...
#1 opens an instance of Notepad++
#2 does nothing

Leaving in the ` ;#1 and ;#2` comment tags and using Code Runner, I see this in the Console Output ...

```ahk
[Running] autohotkey "c:\Users\fade2gray\Documents\AutoHotKey\test.ahk"
'autohotkey' is not recognized as an internal or external command,
operable program or batch file.

[Done] exited with code=1 in 0.059 seconds
```

Removing the ` ;#1 and ;#2` comment tags and using Code Runner, I see this in the Console Output ...

```
[Running] autohotkey "c:\Users\fade2gray\Documents\AutoHotKey\tempCodeRunnerFile.ahk"
'autohotkey' is not recognized as an internal or external command,
operable program or batch file.

[Done] exited with code=1 in 0.047 seconds
```

In neither case did Code Runner open an instance of Notepad++ or  VSCode.

**Comment by FuPeiJiang** [comment]
> Are you sure there should be a leading semicolon on the first line?

I just commented one out to test them individually
___
`'autohotkey' is not recognized as an internal or external command,` because autohotkey isn't in %PATH%
if your autohotkey.exe is in `C:\Program Files\AutoHotkey`, add `C:\Program Files\AutoHotkey` to %PATH%
___
ty for testing

**Comment by eb0687** [comment]
I do apologize for the late reply.

@fade2gray yes you are correct, I wrote the line wrong, this is what I meant to type:
`!^1::Run, "C:\Program Files\Notepad++\notepad++.exe"`

@FuPeiJiang 
Well, it is working now not sure what I did though.
Basically, the issue was that every time I assign a hotkey to run a .exe file it would not work. 
The strange thing is other parts of my code were working fine, except for launching .exe files.

If I can reproduce the issue again in the future il share it here.

Thanks again for the feedback guys.
